name: Gh-Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /flutter_rfw_demo/
          webRenderer: canvaskit
          customArgs: --no-tree-shake-icons && npx -y esbuild ./**/flutter_bootstrap.js --target=chrome83 --outdir=. --outbase=. --allow-overwrite
